apiVersion: apps/v1
kind: Deployment
metadata: 
  name: league-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: league
  template:
    metadata: 
      labels:
        app: league
    spec:
      containers:
        - name: league
          image: barrypr14/yahoo-nba-fantasy-league
          env: 
            - name: MONGO_URI
              value: 'mongodb://league-mongo-srv:27017/league'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: league-srv
spec:
  selector:
    app: league
  ports:
    - name: league
      protocol: TCP
      port: 3000
      targetPort: 3000