apiVersion: apps/v1
kind: Deployment
metadata: 
  name: team-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team
  template:
    metadata: 
      labels:
        app: team
    spec:
      containers:
        - name: team
          image: barrypr14/yahoo-nba-fantasy-team
          env: 
            - name: MONGO_URI
              value: 'mongodb://team-mongo-srv:27017/team'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-username
                  key: USERNAME
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-password
                  key: PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: team-srv
spec:
  selector:
    app: team
  ports:
    - name: team
      protocol: TCP
      port: 3000
      targetPort: 3000